// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SitePrefixUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SitePrefixUpdateRequest{}

// SitePrefixUpdateRequest struct for SitePrefixUpdateRequest
type SitePrefixUpdateRequest struct {
	// ASCII name without leading or trailing whitespace.
	Name *string `json:"name,omitempty"`
	// Optional description. On PATCH, omission or null preserves it; an empty string clears it.
	Description NullableString `json:"description,omitempty"`
}

// NewSitePrefixUpdateRequest instantiates a new SitePrefixUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSitePrefixUpdateRequest() *SitePrefixUpdateRequest {
	this := SitePrefixUpdateRequest{}
	return &this
}

// NewSitePrefixUpdateRequestWithDefaults instantiates a new SitePrefixUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSitePrefixUpdateRequestWithDefaults() *SitePrefixUpdateRequest {
	this := SitePrefixUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SitePrefixUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SitePrefixUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SitePrefixUpdateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SitePrefixUpdateRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SitePrefixUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SitePrefixUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *SitePrefixUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *SitePrefixUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *SitePrefixUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *SitePrefixUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

func (o SitePrefixUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SitePrefixUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return toSerialize, nil
}

type NullableSitePrefixUpdateRequest struct {
	value *SitePrefixUpdateRequest
	isSet bool
}

func (v NullableSitePrefixUpdateRequest) Get() *SitePrefixUpdateRequest {
	return v.value
}

func (v *NullableSitePrefixUpdateRequest) Set(val *SitePrefixUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSitePrefixUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSitePrefixUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSitePrefixUpdateRequest(val *SitePrefixUpdateRequest) *NullableSitePrefixUpdateRequest {
	return &NullableSitePrefixUpdateRequest{value: val, isSet: true}
}

func (v NullableSitePrefixUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSitePrefixUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
