// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SitePrefixQuota type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SitePrefixQuota{}

// SitePrefixQuota struct for SitePrefixQuota
type SitePrefixQuota struct {
	Used  uint32 `json:"used"`
	Limit uint32 `json:"limit"`
}

type _SitePrefixQuota SitePrefixQuota

// NewSitePrefixQuota instantiates a new SitePrefixQuota object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSitePrefixQuota(used uint32, limit uint32) *SitePrefixQuota {
	this := SitePrefixQuota{}
	this.Used = used
	this.Limit = limit
	return &this
}

// NewSitePrefixQuotaWithDefaults instantiates a new SitePrefixQuota object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSitePrefixQuotaWithDefaults() *SitePrefixQuota {
	this := SitePrefixQuota{}
	return &this
}

// GetUsed returns the Used field value
func (o *SitePrefixQuota) GetUsed() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *SitePrefixQuota) GetUsedOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *SitePrefixQuota) SetUsed(v uint32) {
	o.Used = v
}

// GetLimit returns the Limit field value
func (o *SitePrefixQuota) GetLimit() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *SitePrefixQuota) GetLimitOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *SitePrefixQuota) SetLimit(v uint32) {
	o.Limit = v
}

func (o SitePrefixQuota) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SitePrefixQuota) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["used"] = o.Used
	toSerialize["limit"] = o.Limit
	return toSerialize, nil
}

func (o *SitePrefixQuota) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"used",
		"limit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSitePrefixQuota := _SitePrefixQuota{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSitePrefixQuota)

	if err != nil {
		return err
	}

	*o = SitePrefixQuota(varSitePrefixQuota)

	return err
}

type NullableSitePrefixQuota struct {
	value *SitePrefixQuota
	isSet bool
}

func (v NullableSitePrefixQuota) Get() *SitePrefixQuota {
	return v.value
}

func (v *NullableSitePrefixQuota) Set(val *SitePrefixQuota) {
	v.value = val
	v.isSet = true
}

func (v NullableSitePrefixQuota) IsSet() bool {
	return v.isSet
}

func (v *NullableSitePrefixQuota) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSitePrefixQuota(val *SitePrefixQuota) *NullableSitePrefixQuota {
	return &NullableSitePrefixQuota{value: val, isSet: true}
}

func (v NullableSitePrefixQuota) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSitePrefixQuota) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
