// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SitePrefixCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SitePrefixCreateRequest{}

// SitePrefixCreateRequest struct for SitePrefixCreateRequest
type SitePrefixCreateRequest struct {
	// ASCII name without leading or trailing whitespace.
	Name string `json:"name"`
	// Optional description. On PATCH, omission or null preserves it; an empty string clears it.
	Description NullableString `json:"description,omitempty"`
	SiteId      string         `json:"siteId"`
	// Network-aligned IPv4 CIDR wholly inside 10.0.0.0/8, 172.16.0.0/12, or 192.168.0.0/16, with prefix length /8 through /31. Host bits, IPv6, public ranges, and shared address space are rejected. This is private east/west space, not public-IP ownership or permission to advertise BGP routes.
	Prefix string `json:"prefix"`
}

type _SitePrefixCreateRequest SitePrefixCreateRequest

// NewSitePrefixCreateRequest instantiates a new SitePrefixCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSitePrefixCreateRequest(name string, siteId string, prefix string) *SitePrefixCreateRequest {
	this := SitePrefixCreateRequest{}
	this.Name = name
	this.SiteId = siteId
	this.Prefix = prefix
	return &this
}

// NewSitePrefixCreateRequestWithDefaults instantiates a new SitePrefixCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSitePrefixCreateRequestWithDefaults() *SitePrefixCreateRequest {
	this := SitePrefixCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *SitePrefixCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SitePrefixCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SitePrefixCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SitePrefixCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SitePrefixCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *SitePrefixCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *SitePrefixCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *SitePrefixCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *SitePrefixCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetSiteId returns the SiteId field value
func (o *SitePrefixCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SitePrefixCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SitePrefixCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetPrefix returns the Prefix field value
func (o *SitePrefixCreateRequest) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *SitePrefixCreateRequest) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *SitePrefixCreateRequest) SetPrefix(v string) {
	o.Prefix = v
}

func (o SitePrefixCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SitePrefixCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["siteId"] = o.SiteId
	toSerialize["prefix"] = o.Prefix
	return toSerialize, nil
}

func (o *SitePrefixCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"siteId",
		"prefix",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSitePrefixCreateRequest := _SitePrefixCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSitePrefixCreateRequest)

	if err != nil {
		return err
	}

	*o = SitePrefixCreateRequest(varSitePrefixCreateRequest)

	return err
}

type NullableSitePrefixCreateRequest struct {
	value *SitePrefixCreateRequest
	isSet bool
}

func (v NullableSitePrefixCreateRequest) Get() *SitePrefixCreateRequest {
	return v.value
}

func (v *NullableSitePrefixCreateRequest) Set(val *SitePrefixCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSitePrefixCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSitePrefixCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSitePrefixCreateRequest(val *SitePrefixCreateRequest) *NullableSitePrefixCreateRequest {
	return &NullableSitePrefixCreateRequest{value: val, isSet: true}
}

func (v NullableSitePrefixCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSitePrefixCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
