// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SitePrefix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SitePrefix{}

// SitePrefix struct for SitePrefix
type SitePrefix struct {
	Id              string         `json:"id"`
	Name            string         `json:"name"`
	Description     NullableString `json:"description"`
	SiteId          string         `json:"siteId"`
	TenantId        string         `json:"tenantId"`
	Prefix          string         `json:"prefix"`
	Authority       string         `json:"authority"`
	ProtocolVersion string         `json:"protocolVersion"`
	RoutingType     string         `json:"routingType"`
	Status          string         `json:"status"`
	// Latest observed Core lifecycle; null before a Core response or inventory observation.
	CoreStatus NullableString `json:"coreStatus"`
	// Tenant-safe recovery guidance. An unknown result is not proof that the Core operation failed. Retry the same create, PATCH, or DELETE to recover its persisted operation.
	RetryMessage NullableString `json:"retryMessage"`
	// First accepted retirement intent. It remains set even when older Core inventory reports Ready.
	RetirementRequestedAt NullableTime `json:"retirementRequestedAt"`
	// Latest Core-reported point-in-time usage for the owning tenant at this Site; null until Core reports it. Admission remains authoritative.
	Quota NullableSitePrefixQuota `json:"quota"`
	// Active child VPC Prefix IDs owned by this tenant at this Site. Empty when none are known.
	VpcPrefixIds  []string       `json:"vpcPrefixIds"`
	StatusHistory []StatusDetail `json:"statusHistory"`
	Created       time.Time      `json:"created"`
	Updated       time.Time      `json:"updated"`
}

type _SitePrefix SitePrefix

// NewSitePrefix instantiates a new SitePrefix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSitePrefix(id string, name string, description NullableString, siteId string, tenantId string, prefix string, authority string, protocolVersion string, routingType string, status string, coreStatus NullableString, retryMessage NullableString, retirementRequestedAt NullableTime, quota NullableSitePrefixQuota, vpcPrefixIds []string, statusHistory []StatusDetail, created time.Time, updated time.Time) *SitePrefix {
	this := SitePrefix{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.SiteId = siteId
	this.TenantId = tenantId
	this.Prefix = prefix
	this.Authority = authority
	this.ProtocolVersion = protocolVersion
	this.RoutingType = routingType
	this.Status = status
	this.CoreStatus = coreStatus
	this.RetryMessage = retryMessage
	this.RetirementRequestedAt = retirementRequestedAt
	this.Quota = quota
	this.VpcPrefixIds = vpcPrefixIds
	this.StatusHistory = statusHistory
	this.Created = created
	this.Updated = updated
	return &this
}

// NewSitePrefixWithDefaults instantiates a new SitePrefix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSitePrefixWithDefaults() *SitePrefix {
	this := SitePrefix{}
	return &this
}

// GetId returns the Id field value
func (o *SitePrefix) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SitePrefix) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SitePrefix) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SitePrefix) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SitePrefix) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SitePrefix) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *SitePrefix) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetSiteId returns the SiteId field value
func (o *SitePrefix) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SitePrefix) SetSiteId(v string) {
	o.SiteId = v
}

// GetTenantId returns the TenantId field value
func (o *SitePrefix) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *SitePrefix) SetTenantId(v string) {
	o.TenantId = v
}

// GetPrefix returns the Prefix field value
func (o *SitePrefix) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *SitePrefix) SetPrefix(v string) {
	o.Prefix = v
}

// GetAuthority returns the Authority field value
func (o *SitePrefix) GetAuthority() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Authority
}

// GetAuthorityOk returns a tuple with the Authority field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetAuthorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authority, true
}

// SetAuthority sets field value
func (o *SitePrefix) SetAuthority(v string) {
	o.Authority = v
}

// GetProtocolVersion returns the ProtocolVersion field value
func (o *SitePrefix) GetProtocolVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtocolVersion
}

// GetProtocolVersionOk returns a tuple with the ProtocolVersion field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetProtocolVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtocolVersion, true
}

// SetProtocolVersion sets field value
func (o *SitePrefix) SetProtocolVersion(v string) {
	o.ProtocolVersion = v
}

// GetRoutingType returns the RoutingType field value
func (o *SitePrefix) GetRoutingType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoutingType
}

// GetRoutingTypeOk returns a tuple with the RoutingType field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetRoutingTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoutingType, true
}

// SetRoutingType sets field value
func (o *SitePrefix) SetRoutingType(v string) {
	o.RoutingType = v
}

// GetStatus returns the Status field value
func (o *SitePrefix) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SitePrefix) SetStatus(v string) {
	o.Status = v
}

// GetCoreStatus returns the CoreStatus field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SitePrefix) GetCoreStatus() string {
	if o == nil || o.CoreStatus.Get() == nil {
		var ret string
		return ret
	}

	return *o.CoreStatus.Get()
}

// GetCoreStatusOk returns a tuple with the CoreStatus field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SitePrefix) GetCoreStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CoreStatus.Get(), o.CoreStatus.IsSet()
}

// SetCoreStatus sets field value
func (o *SitePrefix) SetCoreStatus(v string) {
	o.CoreStatus.Set(&v)
}

// GetRetryMessage returns the RetryMessage field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SitePrefix) GetRetryMessage() string {
	if o == nil || o.RetryMessage.Get() == nil {
		var ret string
		return ret
	}

	return *o.RetryMessage.Get()
}

// GetRetryMessageOk returns a tuple with the RetryMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SitePrefix) GetRetryMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetryMessage.Get(), o.RetryMessage.IsSet()
}

// SetRetryMessage sets field value
func (o *SitePrefix) SetRetryMessage(v string) {
	o.RetryMessage.Set(&v)
}

// GetRetirementRequestedAt returns the RetirementRequestedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *SitePrefix) GetRetirementRequestedAt() time.Time {
	if o == nil || o.RetirementRequestedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.RetirementRequestedAt.Get()
}

// GetRetirementRequestedAtOk returns a tuple with the RetirementRequestedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SitePrefix) GetRetirementRequestedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetirementRequestedAt.Get(), o.RetirementRequestedAt.IsSet()
}

// SetRetirementRequestedAt sets field value
func (o *SitePrefix) SetRetirementRequestedAt(v time.Time) {
	o.RetirementRequestedAt.Set(&v)
}

// GetQuota returns the Quota field value
// If the value is explicit nil, the zero value for SitePrefixQuota will be returned
func (o *SitePrefix) GetQuota() SitePrefixQuota {
	if o == nil || o.Quota.Get() == nil {
		var ret SitePrefixQuota
		return ret
	}

	return *o.Quota.Get()
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SitePrefix) GetQuotaOk() (*SitePrefixQuota, bool) {
	if o == nil {
		return nil, false
	}
	return o.Quota.Get(), o.Quota.IsSet()
}

// SetQuota sets field value
func (o *SitePrefix) SetQuota(v SitePrefixQuota) {
	o.Quota.Set(&v)
}

// GetVpcPrefixIds returns the VpcPrefixIds field value
func (o *SitePrefix) GetVpcPrefixIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.VpcPrefixIds
}

// GetVpcPrefixIdsOk returns a tuple with the VpcPrefixIds field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetVpcPrefixIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VpcPrefixIds, true
}

// SetVpcPrefixIds sets field value
func (o *SitePrefix) SetVpcPrefixIds(v []string) {
	o.VpcPrefixIds = v
}

// GetStatusHistory returns the StatusHistory field value
func (o *SitePrefix) GetStatusHistory() []StatusDetail {
	if o == nil {
		var ret []StatusDetail
		return ret
	}

	return o.StatusHistory
}

// GetStatusHistoryOk returns a tuple with the StatusHistory field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetStatusHistoryOk() ([]StatusDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusHistory, true
}

// SetStatusHistory sets field value
func (o *SitePrefix) SetStatusHistory(v []StatusDetail) {
	o.StatusHistory = v
}

// GetCreated returns the Created field value
func (o *SitePrefix) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *SitePrefix) SetCreated(v time.Time) {
	o.Created = v
}

// GetUpdated returns the Updated field value
func (o *SitePrefix) GetUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *SitePrefix) GetUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *SitePrefix) SetUpdated(v time.Time) {
	o.Updated = v
}

func (o SitePrefix) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SitePrefix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description.Get()
	toSerialize["siteId"] = o.SiteId
	toSerialize["tenantId"] = o.TenantId
	toSerialize["prefix"] = o.Prefix
	toSerialize["authority"] = o.Authority
	toSerialize["protocolVersion"] = o.ProtocolVersion
	toSerialize["routingType"] = o.RoutingType
	toSerialize["status"] = o.Status
	toSerialize["coreStatus"] = o.CoreStatus.Get()
	toSerialize["retryMessage"] = o.RetryMessage.Get()
	toSerialize["retirementRequestedAt"] = o.RetirementRequestedAt.Get()
	toSerialize["quota"] = o.Quota.Get()
	toSerialize["vpcPrefixIds"] = o.VpcPrefixIds
	toSerialize["statusHistory"] = o.StatusHistory
	toSerialize["created"] = o.Created
	toSerialize["updated"] = o.Updated
	return toSerialize, nil
}

func (o *SitePrefix) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"siteId",
		"tenantId",
		"prefix",
		"authority",
		"protocolVersion",
		"routingType",
		"status",
		"coreStatus",
		"retryMessage",
		"retirementRequestedAt",
		"quota",
		"vpcPrefixIds",
		"statusHistory",
		"created",
		"updated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	nullableRequiredProperties := map[string]struct{}{
		"description":           {},
		"coreStatus":            {},
		"retryMessage":          {},
		"retirementRequestedAt": {},
		"quota":                 {},
	}
	for _, requiredProperty := range requiredProperties {
		_, nullable := nullableRequiredProperties[requiredProperty]
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSitePrefix := _SitePrefix{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSitePrefix)

	if err != nil {
		return err
	}

	*o = SitePrefix(varSitePrefix)

	return err
}

type NullableSitePrefix struct {
	value *SitePrefix
	isSet bool
}

func (v NullableSitePrefix) Get() *SitePrefix {
	return v.value
}

func (v *NullableSitePrefix) Set(val *SitePrefix) {
	v.value = val
	v.isSet = true
}

func (v NullableSitePrefix) IsSet() bool {
	return v.isSet
}

func (v *NullableSitePrefix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSitePrefix(val *SitePrefix) *NullableSitePrefix {
	return &NullableSitePrefix{value: val, isSet: true}
}

func (v NullableSitePrefix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSitePrefix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
